package: lazyload
version: '0.1.1'
author: eaCe
supportpage: /

page:
  title: 'LazyLoad'
  icon: rex-icon fa-spinner
  subpages:
      settings: { title: 'translate:lazyload_setting',perm: lazyload[] }
